import type { ReactNode } from 'react';
import { Download, LockKeyhole, Mic2 } from 'lucide-react';
import type { BlogNode } from '@/lib/blog-data';

export function ContentRenderer({
  document,
  canAccessPrivate = false,
}: {
  document: BlogNode;
  canAccessPrivate?: boolean;
}) {
  return (
    <div className="study-content">
      {document.content?.map((node, index) =>
        renderNode(node, index, canAccessPrivate),
      )}
    </div>
  );
}

function renderNode(
  node: BlogNode,
  key: number | string,
  canAccessPrivate: boolean,
): ReactNode {
  const children = node.content?.map((child, index) =>
    renderNode(child, index, canAccessPrivate),
  );

  switch (node.type) {
    case 'text':
      return applyMarks(node.text ?? '', node.marks ?? [], key);
    case 'paragraph':
      return <p key={key}>{children || <br />}</p>;
    case 'heading': {
      const level = Math.min(3, Math.max(1, numberAttr(node, 'level', 2)));
      if (level === 1) return <h1 key={key}>{children}</h1>;
      if (level === 3) return <h3 key={key}>{children}</h3>;
      return <h2 key={key}>{children}</h2>;
    }
    case 'bulletList':
      return <ul key={key}>{children}</ul>;
    case 'orderedList':
      return <ol key={key}>{children}</ol>;
    case 'listItem':
      return <li key={key}>{children}</li>;
    case 'blockquote':
      return <blockquote key={key}>{children}</blockquote>;
    case 'codeBlock':
      return (
        <pre key={key}>
          <code>{children}</code>
        </pre>
      );
    case 'hardBreak':
      return <br key={key} />;
    case 'horizontalRule':
      return <hr key={key} />;
    case 'image': {
      const imageWidth = optionalNumberAttr(node, 'width');
      const imageHeight = optionalNumberAttr(node, 'height');
      return (
        <figure
          key={key}
          className="rendered-resizable-media"
          style={{
            width: imageWidth ? `${imageWidth}px` : undefined,
            height: imageHeight ? `${imageHeight}px` : undefined,
          }}
        >
          {/* The image source is generated by the trusted media API. */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={stringAttr(node, 'src')}
            alt={stringAttr(node, 'alt') || '게시글 이미지'}
          />
          {stringAttr(node, 'title') && (
            <figcaption>{stringAttr(node, 'title')}</figcaption>
          )}
        </figure>
      );
    }
    case 'media':
      return renderMedia(node, key, canAccessPrivate);
    default:
      return <div key={key}>{children}</div>;
  }
}

function renderMedia(
  node: BlogNode,
  key: number | string,
  canAccessPrivate: boolean,
) {
  const kind = stringAttr(node, 'kind');
  const src = stringAttr(node, 'src');
  const name = stringAttr(node, 'name') || '첨부 파일';
  const width = optionalNumberAttr(node, 'width');
  const height = optionalNumberAttr(node, 'height');

  if (kind === 'audio' && !canAccessPrivate) {
    return (
      <div key={key} className="private-audio">
        <LockKeyhole className="size-4" />
        <div>
          <strong>비공개 수업 녹음</strong>
          <span>관리자만 재생하고 다운로드할 수 있습니다.</span>
        </div>
      </div>
    );
  }

  return (
    <figure
      key={key}
      className="media-attachment rendered-resizable-media"
      style={{
        width: width ? `${width}px` : undefined,
        height: height ? `${height}px` : undefined,
      }}
    >
      <div className="media-attachment__label">
        {kind === 'audio' ? <Mic2 className="size-4" /> : null}
        <span>{name}</span>
        <a href={src + '?download=1'} download>
          <Download className="size-3.5" />
          다운로드
        </a>
      </div>
      {kind === 'audio' ? (
        // Recorded lecture audio does not have a caption track at upload time.
        // oxlint-disable-next-line jsx-a11y/media-has-caption
        <audio src={src} controls preload="metadata" />
      ) : null}
      {kind === 'video' ? (
        // User-uploaded video may not include a separate WebVTT track.
        // oxlint-disable-next-line jsx-a11y/media-has-caption
        <video src={src} controls preload="metadata" />
      ) : null}
    </figure>
  );
}

function applyMarks(
  text: string,
  marks: Array<{ type: string; attrs?: Record<string, unknown> }>,
  key: number | string,
) {
  let content: ReactNode = text;
  for (const mark of marks) {
    if (mark.type === 'bold') content = <strong>{content}</strong>;
    if (mark.type === 'italic') content = <em>{content}</em>;
    if (mark.type === 'strike') content = <s>{content}</s>;
    if (mark.type === 'code') content = <code>{content}</code>;
    if (mark.type === 'fontSize') {
      const size = safeFontSize(mark.attrs?.size);
      if (size) content = <span style={{ fontSize: `${size}pt` }}>{content}</span>;
    }
    if (mark.type === 'link') {
      const href = typeof mark.attrs?.href === 'string' ? mark.attrs.href : '#';
      content = (
        <a href={href} rel="noreferrer noopener" target="_blank">
          {content}
        </a>
      );
    }
  }
  return <span key={key}>{content}</span>;
}

function safeFontSize(value: unknown) {
  const size =
    typeof value === 'number'
      ? value
      : typeof value === 'string'
        ? Number.parseFloat(value)
        : Number.NaN;
  return Number.isFinite(size) && size >= 1 && size <= 100 ? size : undefined;
}

function stringAttr(node: BlogNode, key: string) {
  const value = node.attrs?.[key];
  return typeof value === 'string' ? value : '';
}

function numberAttr(node: BlogNode, key: string, fallback: number) {
  const value = node.attrs?.[key];
  return typeof value === 'number' ? value : fallback;
}

function optionalNumberAttr(node: BlogNode, key: string) {
  const value = node.attrs?.[key];
  if (typeof value === 'number' && Number.isFinite(value) && value > 0) {
    return value;
  }
  if (typeof value === 'string') {
    const parsed = Number.parseFloat(value);
    return Number.isFinite(parsed) && parsed > 0 ? parsed : undefined;
  }
  return undefined;
}
