'use client';

import { useEffect, useRef, useState, type ReactNode } from 'react';
import {
  Download,
  LockKeyhole,
  Maximize2,
  Mic2,
  Pause,
  Play,
  Volume2,
  VolumeX,
  X,
} from 'lucide-react';
import type { BlogNode } from '@/lib/blog-data';

export function ContentRenderer({
  document,
  canAccessPrivate = false,
}: {
  document: BlogNode;
  canAccessPrivate?: boolean;
}) {
  return (
    <div className="study-content">
      {document.content?.map((node, index) =>
        renderNode(node, index, canAccessPrivate),
      )}
    </div>
  );
}

function renderNode(
  node: BlogNode,
  key: number | string,
  canAccessPrivate: boolean,
): ReactNode {
  const children = node.content?.map((child, index) =>
    renderNode(child, index, canAccessPrivate),
  );

  switch (node.type) {
    case 'text':
      return applyMarks(node.text ?? '', node.marks ?? [], key);
    case 'paragraph':
      return <p key={key}>{children || <br />}</p>;
    case 'heading': {
      const level = Math.min(3, Math.max(1, numberAttr(node, 'level', 2)));
      if (level === 1) return <h1 key={key}>{children}</h1>;
      if (level === 3) return <h3 key={key}>{children}</h3>;
      return <h2 key={key}>{children}</h2>;
    }
    case 'bulletList':
      return <ul key={key}>{children}</ul>;
    case 'orderedList':
      return <ol key={key}>{children}</ol>;
    case 'listItem':
      return <li key={key}>{children}</li>;
    case 'blockquote':
      return <blockquote key={key}>{children}</blockquote>;
    case 'codeBlock':
      return (
        <pre key={key}>
          <code>{children}</code>
        </pre>
      );
    case 'hardBreak':
      return <br key={key} />;
    case 'horizontalRule':
      return <hr key={key} />;
    case 'image': {
      const imageWidth = optionalNumberAttr(node, 'width');
      const imageHeight = optionalNumberAttr(node, 'height');
      return (
        <figure
          key={key}
          className="rendered-resizable-media"
          style={{
            width: imageWidth ? `${imageWidth}px` : undefined,
            height: imageHeight ? `${imageHeight}px` : undefined,
          }}
        >
          <ReadableImage
            src={stringAttr(node, 'src')}
            alt={stringAttr(node, 'alt') || '게시글 이미지'}
          />
          {stringAttr(node, 'title') && (
            <figcaption>{stringAttr(node, 'title')}</figcaption>
          )}
        </figure>
      );
    }
    case 'media':
      return renderMedia(node, key, canAccessPrivate);
    default:
      return <div key={key}>{children}</div>;
  }
}

function renderMedia(
  node: BlogNode,
  key: number | string,
  canAccessPrivate: boolean,
) {
  const kind = stringAttr(node, 'kind');
  const src = stringAttr(node, 'src');
  const name = stringAttr(node, 'name') || '첨부 파일';
  const width = optionalNumberAttr(node, 'width');
  const height = optionalNumberAttr(node, 'height');

  if (kind === 'audio' && !canAccessPrivate) {
    return (
      <div key={key} className="private-audio">
        <LockKeyhole className="size-4" />
        <div>
          <strong>비공개 수업 녹음</strong>
          <span>관리자만 재생하고 다운로드할 수 있습니다.</span>
        </div>
      </div>
    );
  }

  return (
    <figure
      key={key}
      className="media-attachment rendered-resizable-media"
      style={{
        width: width ? `${width}px` : undefined,
        height: height ? `${height}px` : undefined,
      }}
    >
      <div className="media-attachment__label">
        {kind === 'audio' ? <Mic2 className="size-4" /> : null}
        <span>{name}</span>
        <a href={src + '?download=1'} download>
          <Download className="size-3.5" />
          다운로드
        </a>
      </div>
      {kind === 'audio' ? (
        // Recorded lecture audio does not have a caption track at upload time.
        // oxlint-disable-next-line jsx-a11y/media-has-caption
        <audio src={src} controls preload="metadata" />
      ) : null}
      {kind === 'video' ? (
        <ReadingVideoPlayer src={src} name={name} />
      ) : null}
    </figure>
  );
}

function ReadableImage({ src, alt }: { src: string; alt: string }) {
  const [isOpen, setIsOpen] = useState(false);

  useEffect(() => {
    if (!isOpen) return;
    const closeOnEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape') setIsOpen(false);
    };
    window.addEventListener('keydown', closeOnEscape);
    return () => window.removeEventListener('keydown', closeOnEscape);
  }, [isOpen]);

  return (
    <>
      <button
        type="button"
        className="readable-image-button"
        onClick={() => setIsOpen(true)}
        aria-label={`${alt} 크게 보기`}
        title="클릭하여 크게 보기"
      >
        {/* The image source is generated by the trusted media API. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={src} alt={alt} />
      </button>
      {isOpen ? (
        <dialog
          open
          className="image-lightbox"
          aria-label={`${alt} 확대 이미지`}
        >
          <div className="image-lightbox__actions">
            <button
              type="button"
              onClick={() => setIsOpen(false)}
              aria-label="확대 이미지 닫기"
              title="닫기"
            >
              <X />
            </button>
          </div>
          {/* The image source is generated by the trusted media API. */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img className="image-lightbox__image" src={src} alt={alt} />
        </dialog>
      ) : null}
    </>
  );
}

function ReadingVideoPlayer({ src, name }: { src: string; name: string }) {
  const containerRef = useRef<HTMLDivElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const lastVolumeRef = useRef(1);
  const [paused, setPaused] = useState(true);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [volume, setVolume] = useState(1);
  const [playbackRate, setPlaybackRate] = useState(1);

  function togglePlayback() {
    const video = videoRef.current;
    if (!video) return;
    if (video.paused) {
      void video.play();
    } else {
      video.pause();
    }
  }

  function setVideoVolume(nextVolume: number) {
    const video = videoRef.current;
    if (!video) return;
    const safeVolume = Math.min(1, Math.max(0, nextVolume));
    video.volume = safeVolume;
    video.muted = safeVolume === 0;
    if (safeVolume > 0) lastVolumeRef.current = safeVolume;
    setVolume(safeVolume);
  }

  function toggleMute() {
    setVideoVolume(volume > 0 ? 0 : lastVolumeRef.current || 1);
  }

  async function toggleFullscreen() {
    const container = containerRef.current;
    if (!container) return;
    if (document.fullscreenElement) {
      await document.exitFullscreen();
    } else {
      await container.requestFullscreen();
    }
  }

  return (
    <div ref={containerRef} className="reading-video-player">
      {/* User-uploaded video may not include a separate WebVTT track. */}
      {/* oxlint-disable-next-line jsx-a11y/media-has-caption */}
      <video
        ref={videoRef}
        src={src}
        preload="metadata"
        tabIndex={0}
        aria-label={`${name} 동영상. 클릭하거나 스페이스바로 재생 및 일시정지`}
        onClick={(event) => {
          event.currentTarget.focus();
          togglePlayback();
        }}
        onKeyDown={(event) => {
          if (event.code === 'Space') {
            event.preventDefault();
            togglePlayback();
          }
        }}
        onPlay={() => setPaused(false)}
        onPause={() => setPaused(true)}
        onTimeUpdate={(event) => setCurrentTime(event.currentTarget.currentTime)}
        onLoadedMetadata={(event) =>
          setDuration(Number.isFinite(event.currentTarget.duration) ? event.currentTarget.duration : 0)
        }
        onVolumeChange={(event) => {
          const nextVolume = event.currentTarget.muted
            ? 0
            : event.currentTarget.volume;
          setVolume(nextVolume);
        }}
      />
      <div className="reading-video-controls">
        <button
          type="button"
          onClick={togglePlayback}
          aria-label={paused ? '동영상 재생' : '동영상 일시정지'}
        >
          {paused ? <Play /> : <Pause />}
        </button>
        <input
          type="range"
          min="0"
          max={duration || 0}
          step="0.1"
          value={Math.min(currentTime, duration || 0)}
          onChange={(event) => {
            const nextTime = Number(event.target.value);
            if (videoRef.current) videoRef.current.currentTime = nextTime;
            setCurrentTime(nextTime);
          }}
          aria-label="동영상 재생 위치"
          className="reading-video-controls__progress"
        />
        <span className="reading-video-controls__time">
          {formatMediaTime(currentTime)} / {formatMediaTime(duration)}
        </span>
        <button
          type="button"
          onClick={toggleMute}
          aria-label={volume > 0 ? '동영상 음소거' : '동영상 음소거 해제'}
        >
          {volume > 0 ? <Volume2 /> : <VolumeX />}
        </button>
        <input
          type="range"
          min="0"
          max="1"
          step="0.05"
          value={volume}
          onChange={(event) => setVideoVolume(Number(event.target.value))}
          aria-label="동영상 음량"
          className="reading-video-controls__volume"
        />
        <select
          value={playbackRate}
          onChange={(event) => {
            const rate = Number(event.target.value);
            if (videoRef.current) videoRef.current.playbackRate = rate;
            setPlaybackRate(rate);
          }}
          aria-label="동영상 재생 속도"
          title="재생 속도"
        >
          {[0.5, 0.75, 1, 1.25, 1.5, 2].map((rate) => (
            <option key={rate} value={rate}>
              {rate}×
            </option>
          ))}
        </select>
        <button
          type="button"
          onClick={() => void toggleFullscreen()}
          aria-label="동영상 전체화면"
        >
          <Maximize2 />
        </button>
      </div>
    </div>
  );
}

function formatMediaTime(value: number) {
  if (!Number.isFinite(value) || value < 0) return '0:00';
  const minutes = Math.floor(value / 60);
  const seconds = Math.floor(value % 60);
  return `${minutes}:${String(seconds).padStart(2, '0')}`;
}

function applyMarks(
  text: string,
  marks: Array<{ type: string; attrs?: Record<string, unknown> }>,
  key: number | string,
) {
  let content: ReactNode = text;
  for (const mark of marks) {
    if (mark.type === 'bold') content = <strong>{content}</strong>;
    if (mark.type === 'italic') content = <em>{content}</em>;
    if (mark.type === 'strike') content = <s>{content}</s>;
    if (mark.type === 'code') content = <code>{content}</code>;
    if (mark.type === 'fontSize') {
      const size = safeFontSize(mark.attrs?.size);
      if (size) content = <span style={{ fontSize: `${size}pt` }}>{content}</span>;
    }
    if (mark.type === 'link') {
      const href = typeof mark.attrs?.href === 'string' ? mark.attrs.href : '#';
      content = (
        <a href={href} rel="noreferrer noopener" target="_blank">
          {content}
        </a>
      );
    }
  }
  return <span key={key}>{content}</span>;
}

function safeFontSize(value: unknown) {
  const size =
    typeof value === 'number'
      ? value
      : typeof value === 'string'
        ? Number.parseFloat(value)
        : Number.NaN;
  return Number.isFinite(size) && size >= 1 && size <= 100 ? size : undefined;
}

function stringAttr(node: BlogNode, key: string) {
  const value = node.attrs?.[key];
  return typeof value === 'string' ? value : '';
}

function numberAttr(node: BlogNode, key: string, fallback: number) {
  const value = node.attrs?.[key];
  return typeof value === 'number' ? value : fallback;
}

function optionalNumberAttr(node: BlogNode, key: string) {
  const value = node.attrs?.[key];
  if (typeof value === 'number' && Number.isFinite(value) && value > 0) {
    return value;
  }
  if (typeof value === 'string') {
    const parsed = Number.parseFloat(value);
    return Number.isFinite(parsed) && parsed > 0 ? parsed : undefined;
  }
  return undefined;
}
